
// File generated by FlutterFire CLI. Do not modify.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6TEVHR4Yheb8RlM4Z6-xONMtnsTZU8So',
    appId: '1:549153564292:web:9139cbf2ac2080dcbc44d1',
    messagingSenderId: '549153564292',
    projectId: 'black-rock-2d202',
    authDomain: 'black-rock-2d202.firebaseapp.com',
    databaseURL: 'https://black-rock-2d202-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'black-rock-2d202.appspot.com',
    measurementId: 'G-1CXTMZSSHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6TEVHR4Yheb8RlM4Z6-xONMtnsTZU8So',
    appId: '1:549153564292:android:a2c5a7a5c3b1a8f9bc44d1',
    messagingSenderId: '549153564292',
    projectId: 'black-rock-2d202',
    databaseURL: 'https://black-rock-2d202-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'black-rock-2d202.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6TEVHR4Yheb8RlM4Z6-xONMtnsTZU8So',
    appId: '1:549153564292:ios:f62853684a0c2053bc44d1',
    messagingSenderId: '549153564292',
    projectId: 'black-rock-2d202',
    databaseURL: 'https://black-rock-2d202-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'black-rock-2d202.appspot.com',
    iosBundleId: 'com.example.biznest',
  );
}
